### ISSUE TITLE
Call either gtmOnSucces or gtmOnFailure exactly once every time your template is run

### ISSUE THREAD

**Issue by lanzone1** [ScreebApp/sdk-gtm-browser#1]
When reviewing your template we've noticed that gtmOnSuccess or gtmOnFailure are called incorrectly. This is required so that users can sequence their tags correctly. What you have is:

```
injectScript(url, data.gtmOnSuccess(), data.gtmOnFailure(), url);
```
This will result in both `gtmOnSuccess` and `gtmOnFailure` always being called. 

I think what you want is (note the lack of parentheses):
```
injectScript(url, data.gtmOnSuccess, data.gtmOnFailure, url);
```

**Comment by samber** [comment]
Thanks for the review. 

I just made a fix and the changelog has been updated. ✅

**Comment by lanzone1** [comment]
Great. Thanks!
